import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Invest with Us",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            background: "url('/assets/stars.svg')",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
